-- ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE는 각각 
-- 온라인 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일

SELECT OS.USER_ID, OS.PRODUCT_ID
FROM ONLINE_SALE OS
GROUP BY OS.USER_ID, OS.PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY OS.USER_ID ASC, OS.PRODUCT_ID DESC;