-- ID, FISH_TYPE, LENGTH, TIME은 각각 잡은 
-- 물고기의 ID, 물고기의 종류(숫자), 잡은 물고기의 길이(cm), 물고기를 잡은 날짜

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');
